In [1]:
from tensorflow.keras.applications import inception_v3, resnet, vgg16
from tensorflow.keras.preprocessing import image
import numpy as np
import tensorflow as tf

In [2]:
image_path = 'D:/hccho/TF2/creative_commons_elephant.jpg'
inception_image_size = (299,299)
img = image.load_img(image_path).resize(inception_image_size)   # PIL.JpegImagePlugin.JpegImageFile image

img = image.img_to_array(img)   # type은 float32 이지만, 값은 0~255값.
img = np.expand_dims(img, axis=0)
inception_img = inception_v3.preprocess_input(img)
inception_img

array([[[[ 0.5372549 ,  0.6784314 ,  0.8352941 ],
         [ 0.52156866,  0.67058825,  0.81960785],
         [ 0.5294118 ,  0.6784314 ,  0.8117647 ],
         ...,
         [ 0.48235297,  0.58431375,  0.73333335],
         [ 0.47450984,  0.5764706 ,  0.7254902 ],
         [ 0.4666667 ,  0.5686275 ,  0.7176471 ]],

        [[ 0.5372549 ,  0.6784314 ,  0.8352941 ],
         [ 0.5372549 ,  0.6862745 ,  0.81960785],
         [ 0.5294118 ,  0.6784314 ,  0.8117647 ],
         ...,
         [ 0.48235297,  0.58431375,  0.73333335],
         [ 0.47450984,  0.5764706 ,  0.7254902 ],
         [ 0.4666667 ,  0.5686275 ,  0.7176471 ]],

        [[ 0.5372549 ,  0.6784314 ,  0.8352941 ],
         [ 0.5372549 ,  0.6862745 ,  0.81960785],
         [ 0.5372549 ,  0.6862745 ,  0.81960785],
         ...,
         [ 0.4666667 ,  0.5686275 ,  0.7176471 ],
         [ 0.4666667 ,  0.5686275 ,  0.7176471 ],
         [ 0.47450984,  0.5764706 ,  0.7254902 ]],

        ...,

        [[-0.18431371, -0.11372548, -0

In [3]:
def preprocess_image(image_path,base_model,image_size):
    # 사진을 열고 크기를 줄이고 인셉션 V3가 인식하는 텐서 포맷으로 변환하는 유틸리티 함수
    img = image.load_img(image_path).resize(image_size)   # PIL.JpegImagePlugin.JpegImageFile image

    img = image.img_to_array(img)   # type은 float32 이지만, 값은 0~255값.
    img = np.expand_dims(img, axis=0)

    img = base_model.preprocess_input(img)  # 이미지  크기가 변하지 않는다.   ===> numpy array(tensor아님). 

    # return한 값의 범위는 모델에 따라 다르다.
    # inception: -1~1 사이값              resnet: -118.68 ~ 141.061 사이값(0~1사이값 아님)             vgg16: -118.68 ~ 141.061 사이값(0~1사이값 아님) 
    return img  

In [4]:
flag='resnet'
if flag == 'inception':
    model = inception_v3.InceptionV3(weights='imagenet',include_top=True)  # include_top = True/False에 따라, weight 파일이 다르다.
    base_model = inception_v3
    image_size = (299,299)     # tuple(model.input.shape )[1:3]
elif flag =='resnet':
    # weights: None(random initialization), 'imagenet'(pre-training on ImageNet), or the path to the weights file
    # include_top: whether to include the fully-connected layer at the top of the network.
    model = resnet.ResNet50(weights='imagenet',include_top=True)  # 100M, Trainable params: 25,583,592
    base_model = resnet
    image_size = (224,224)    # tuple(model.input.shape )[1:3]
elif flag == 'vgg16':
    model = vgg16.VGG16(weights='imagenet',include_top=True)  # 100M 
    base_model = vgg16
    image_size = (224,224)    # tuple(model.input.shape )[1:3]    

In [5]:
model.input

<tf.Tensor 'input_1:0' shape=(None, 224, 224, 3) dtype=float32>

In [6]:
print(model.summary())
base_image_path = 'D:/hccho/TF2/creative_commons_elephant.jpg'   # './original_photo_deep_dream.jpg'    './creative_commons_elephant.jpg'
img = preprocess_image(base_image_path, base_model,image_size)

Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, 112, 112, 64) 256         conv1_conv[0][0]                 
___________________________________________________________________________________________

In [7]:
print('preprocessed: ', img.shape)
img

preprocessed:  (1, 224, 224, 3)


array([[[[129.061     ,  97.221     ,  71.32      ],
         [127.061     ,  97.221     ,  71.32      ],
         [127.061     ,  97.221     ,  71.32      ],
         ...,
         [117.061     ,  85.221     ,  65.32      ],
         [116.061     ,  84.221     ,  64.32      ],
         [115.061     ,  83.221     ,  63.32      ]],

        [[129.061     ,  97.221     ,  72.32      ],
         [128.061     ,  98.221     ,  72.32      ],
         [128.061     ,  98.221     ,  72.32      ],
         ...,
         [116.061     ,  84.221     ,  64.32      ],
         [115.061     ,  83.221     ,  63.32      ],
         [115.061     ,  83.221     ,  63.32      ]],

        [[128.061     ,  97.221     ,  72.32      ],
         [128.061     ,  98.221     ,  72.32      ],
         [128.061     ,  98.221     ,  72.32      ],
         ...,
         [116.061     ,  84.221     ,  64.32      ],
         [115.061     ,  83.221     ,  63.32      ],
         [116.061     ,  84.221     ,  64.32      ]],

In [8]:
out = model(img)  # tensor ---> softmax가 취해진 값
preds = model.predict(img)  # np.array  ---> 값은 위의 out과 동일
print(out.shape, np.argmax(preds,axis=1))
print(base_model.decode_predictions(preds, top=3))  # preds로 부터 top 3를 추출해 준다. preds대신 out.numpy()를 넘겨도 된다.

(1, 1000) [386]
[[('n02504458', 'African_elephant', 0.80415183), ('n02408429', 'water_buffalo', 0.10159651), ('n01871265', 'tusker', 0.07317309)]]


In [9]:
preds

array([[4.77065356e-08, 1.44275480e-09, 2.26191599e-08, 3.57842218e-08,
        3.22007168e-08, 1.29652364e-07, 8.25588486e-08, 7.80637151e-07,
        4.56880365e-08, 7.85141219e-06, 2.22688534e-09, 5.88033711e-09,
        3.36300010e-09, 1.22116373e-09, 1.04554783e-08, 5.27856834e-08,
        4.89056973e-09, 1.26455317e-08, 1.49110463e-07, 7.46304796e-09,
        6.61077593e-08, 1.51266408e-06, 7.72572903e-08, 1.61307125e-05,
        1.78060038e-08, 9.66312257e-08, 2.73273493e-08, 3.00942808e-08,
        1.59213069e-08, 2.49300065e-08, 2.86661272e-09, 1.06317555e-09,
        3.79116027e-09, 1.30975778e-07, 1.19018935e-07, 5.61191271e-09,
        6.35175184e-08, 1.04303020e-08, 2.34346302e-08, 6.19340454e-08,
        1.65937197e-09, 5.11898213e-09, 4.41042545e-08, 2.28371789e-07,
        3.09529575e-08, 2.26519710e-08, 2.62991473e-09, 5.43601928e-08,
        3.12132642e-07, 1.05005602e-05, 4.05854337e-08, 2.26329612e-05,
        1.00510809e-08, 2.19349108e-08, 1.38506977e-07, 1.479394

# Transfer Learning

In [10]:
model = resnet.ResNet50(weights='imagenet',include_top=False)

In [11]:
model.summary()

Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, None, None,  0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, None, None, 3 0           input_2[0][0]                    
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, None, None, 6 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, None, None, 6 256         conv1_conv[0][0]                 
___________________________________________________________________________________________

In [12]:
output_layer =model.get_layer('conv5_block3_3_conv')

In [13]:
model.input,output_layer.output

(<tf.Tensor 'input_2:0' shape=(None, None, None, 3) dtype=float32>,
 <tf.Tensor 'conv5_block3_3_conv/BiasAdd_1:0' shape=(None, None, None, 2048) dtype=float32>)

In [14]:
pre_model = tf.keras.Model(inputs = model.input,outputs = output_layer.output)

In [25]:
pre_model.trainable=False

In [17]:
pre_model(img).shape

TensorShape([1, 2048])

In [22]:
model = tf.keras.models.Sequential([pre_model,
                                    tf.keras.layers.GlobalAveragePooling2D(),  # squeeze는 불필요
                                    tf.keras.layers.Dense(units=100,input_dim=3,activation='relu'),
                                    tf.keras.layers.Dense(units=5,activation=None)])

In [23]:
model(img)

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[ 0.03789362, -0.20322965, -0.14062066,  0.0848752 ,  0.19154021]],
      dtype=float32)>